# Generated by Django 6.0 on 2025-12-11 20:34

from django.db import migrations, models
from django.utils.text import slugify # 🚨 Nuevo: Necesario para generar los slugs
import django.utils.timezone


# 🚨 NUEVA FUNCIÓN CRÍTICA: Rellena los slugs de las categorías existentes 🚨
def generar_slug_categorias(apps, schema_editor):
    # Obtenemos el modelo Categoria del estado histórico de la migración
    Categoria = apps.get_model('publicaciones', 'Categoria')
    
    # Recorremos todas las categorías existentes
    for categoria in Categoria.objects.all():
        # Generamos el slug a partir del nombre, asegurando un valor único y válido
        categoria.slug = slugify(categoria.nombre)
        # Guardamos solo el slug, para evitar ejecutar la lógica de 'save()' del modelo completo
        categoria.save(update_fields=['slug'])
        
# -------------------------------------------------------------

class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        # PASO 1: Añadir el campo slug. Lo definimos como NULL=True TEMPORALMENTE 
        # para que SQLite pueda añadir la columna sin fallar inmediatamente al copiar las filas.
        # Quitamos la restricción unique=True por ahora, la aplicaremos después de rellenar.
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        
        # 🚨 PASO 2: Ejecutar la función Python para rellenar los slugs de los datos existentes 🚨
        migrations.RunPython(generar_slug_categorias, migrations.RunPython.noop),
        
        # PASO 3: AlterField para hacer el campo UNIQUE y NO NULO, ya que ahora está rellenado.
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),

        # Mantenemos tu AlterField original para Publicacion
        migrations.AlterField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='fecha_creacion'),
        ),
    ]
